### ISSUE TITLE
pre-commit failure

### ISSUE THREAD

**Issue by sibirrer** [LSST-strong-lensing/slsim#121]
pre-commit fails in multiple very recent PRs, i.e. https://github.com/LSST-strong-lensing/slsim/pull/120#issuecomment-1902665801

> I'm unsure why my pre-commit is failing, the message is:
> 
> * hook id: ruff
> * exit code: 2
> 
> ruff failed Cause: Failed to create cache file '/code/.ruff_cache/0.1.12/14578334182369668236' Cause: No such file or directory (os error 2)
> 
> I ran the usual lines of code to make sure the formatting was proper, specifically:
> 
> ```
> black .
> docformatter ./* -r --black --in-place
> ```
> 
> There are minor warnings that come up in my test functions due to undefined temperature regions, but I don't think this should be causing this error.

There was a noticed issue with pre-commit version 0.1.12 but now the requirement for GitHub Actions is 0.1.13. What makes me wonder is why a cache file with 0.1.12 gets generated.

**Comment by ajshajib** [comment]
This should be fixed with #122. Closing this now, but please reopen if the error persists.
