### ISSUE TITLE
Readthedocs build failing?

### ISSUE THREAD

**Issue by BrunoSanchez** [LSST-strong-lensing/slsim#204]
It seems that the most recent build in readthedocs is now 8 months old.
Is there an issue that is preventing the most recent documentation to build in the server?

**Comment by sibirrer** [comment]
Thank you for checking @BrunoSanchez . The web hook was pointing at a wrong point. I updated it and manually run a build.  It fails, see https://readthedocs.org/projects/slsim/builds/25039124/ due to the notebook configurations not being installed

**Comment by BrunoSanchez** [comment]
Thanks for the fix on the hook config.
I was expecting the need to re-configure some extensions, this is very common. Will try to get a fix for this asap.

**Comment by sibirrer** [comment]
@nkhadka21 and I fixed it. Haven't checked though whether the notebooks display well

**Comment by BrunoSanchez** [comment]
I don't see the section in the readthedocs at all. It seems like it is not building the correct branch?

**Comment by sibirrer** [comment]
The built are certainly happening: https://readthedocs.org/projects/slsim/builds/25044163/ I just don't know what configuration would need to change to display the notebooks

**Comment by nkhadka21** [comment]
Thank you very much @BrunoSanchez for solving notebook issues! I think we resolved this issue. So, I am closing this. Please feel free to open it again if necessary.
