### ISSUE TITLE
Error in test_lens_pop.py

### ISSUE THREAD

**Issue by luisleonanaya** [LSST-strong-lensing/slsim#249]
Hello @nkhadka21 when trying to run "https://data.lsst.cloud/nb/user/luisleonanaya/files/projects/slsim_pruebas/tests/test_lens_pop.py", I get multiple errors, thanks in advance:                                                                                                                                                                       
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.11.9, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/luisleonanaya/projects/slsim_pruebas
plugins: session2file-0.1.11, astropy-header-0.2.2, subtests-0.13.1, arraydiff-0.6.1, time-machine-2.15.0, asdf-3.4.0, hypothesis-6.111.1, filter-subpackage-0.2.0, doctestplus-1.2.1, vcr-1.0.2, openfiles-0.5.0, cov-5.0.0, remotedata-0.4.1, anyio-4.4.0, typeguard-4.3.0, xdist-3.6.1, astropy-0.11.0, mock-3.14.0, dash-2.17.1, nbval-0.11.0
collecting 125 items / 2 errors                                                                                        collected 290 items / 5 errors                                                                                                                                            

================================================================================= ERRORS ==================================================================================
____________________________________________________ ERROR collecting tests/test_Deflectors/test_cluster_deflectors.py ____________________________________________________
ImportError while importing test module '/home/luisleonanaya/projects/slsim_pruebas/tests/test_Deflectors/test_cluster_deflectors.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/lsst/software/stack/conda/envs/lsst-scipipe-9.0.0/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_Deflectors/test_cluster_deflectors.py:2: in <module>
    from slsim.Deflectors.cluster_deflectors import ClusterDeflectors
E   ModuleNotFoundError: No module named 'slsim.Deflectors.cluster_deflectors'
______________________________________________________ ERROR collecting tests/test_Deflectors/test_richness2mass.py _______________________________________________________
ImportError while importing test module '/home/luisleonanaya/projects/slsim_pruebas/tests/test_Deflectors/test_richness2mass.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/lsst/software/stack/conda/envs/lsst-scipipe-9.0.0/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_Deflectors/test_richness2mass.py:1: in <module>
    from slsim.Deflectors.richness2mass import mass_richness_relation
E   ModuleNotFoundError: No module named 'slsim.Deflectors.richness2mass'
________________________________________________________________ ERROR collecting tests/test_param_util.py ________________________________________________________________
ImportError while importing test module '/home/luisleonanaya/projects/slsim_pruebas/tests/test_param_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/lsst/software/stack/conda/envs/lsst-scipipe-9.0.0/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_param_util.py:4: in <module>
    from slsim.Util.param_util import (
E   ImportError: cannot import name 'fits_append_table' from 'slsim.Util.param_util' (/home/luisleonanaya/.local/lib/python3.11/site-packages/slsim/Util/param_util.py)
__________________________________________________________ ERROR collecting tests/test_roman_image_simulation.py __________________________________________________________
ImportError while importing test module '/home/luisleonanaya/projects/slsim_pruebas/tests/test_roman_image_simulation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/lsst/software/stack/conda/envs/lsst-scipipe-9.0.0/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_roman_image_simulation.py:4: in <module>
    from slsim.roman_image_simulation import simulate_roman_image
E   ModuleNotFoundError: No module named 'slsim.roman_image_simulation'
________________________________________________________________ ERROR collecting tests/test_selection.py _________________________________________________________________
ImportError while importing test module '/home/luisleonanaya/projects/slsim_pruebas/tests/test_selection.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/lsst/software/stack/conda/envs/lsst-scipipe-9.0.0/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_selection.py:1: in <module>
    from slsim.selection import object_cut
E   ImportError: cannot import name 'object_cut' from 'slsim.selection' (/home/luisleonanaya/.local/lib/python3.11/site-packages/slsim/selection.py)
============================================================================ warnings summary =============================================================================
../../../../../opt/lsst/software/stack/conda/envs/lsst-scipipe-9.0.0/lib/python3.11/site-packages/_pytest/config/__init__.py:1273
  /opt/lsst/software/stack/conda/envs/lsst-scipipe-9.0.0/lib/python3.11/site-packages/_pytest/config/__init__.py:1273: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: asdf
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================= short test summary info =========================================================================
ERROR test_Deflectors/test_cluster_deflectors.py
ERROR test_Deflectors/test_richness2mass.py
ERROR test_param_util.py
ERROR test_roman_image_simulation.py
ERROR test_selection.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================== 1 warning, 5 errors in 46.00s ======================================================================

**Comment by sibirrer** [comment]
@luisleonanaya do you use the main branch of SLSim or a pip version (outdated). Our CIs are passing on the virtual environment set up with Github Actions: https://github.com/LSST-strong-lensing/slsim/actions

**Comment by nkhadka21** [comment]
Hi @luisleonanaya , Thank you very much for bringing this issue here! I updated some of the example notebooks. I hope this will resolve your issue. So, I am closing this issue. If this issue still exist, please feel free to re-open it.
