### ISSUE TITLE
COOLEST format of population lenses

### ISSUE THREAD

**Issue by sibirrer** [LSST-strong-lensing/slsim#36]
COOLEST: https://github.com/aymgal/COOLEST

Generate a function that can return COOLEST format.
lenstronomy also supports this functionality here: 
https://github.com/lenstronomy/lenstronomy/blob/main/lenstronomy/Util/coolest_interface.py

**Comment by sibirrer** [comment]
Lenstronomy has a conversion to COOLEST function here: https://github.com/lenstronomy/lenstronomy/blob/b9d03df087c846566eb9be777cc2e9a0a7e8a751/lenstronomy/Util/coolest_interface.py#L306C37-L306C46

**Comment by nkhadka21** [comment]
We addressed this issue. So, I am closing it now.
