### ISSUE TITLE
documentation pages are not up to date. 

### ISSUE THREAD

**Issue by alxogm** [LSST-strong-lensing/slsim#89]
Hi!, 

When trying to install slsim, I noticed that documentation here: https://slsim.readthedocs.io/en/latest/installation.html  is outdated wrt  https://github.com/LSST-strong-lensing/slsim/blob/main/docs/installation.rst 

The same thing happen for https://slsim.readthedocs.io/en/latest/contributing.html at least. Not a big issue but would be nice to fix it.

also, the instruction 

`git clone git://github.com/LSST-strong-lensing/slsim ` 

didn't work for me, I had to change it to: 

`git clone https://github.com/LSST-strong-lensing/slsim.git`

(which is the usual way I clone repositories)... Not sure if this is an actual issue, or maybe its something particular to my git ?

Finally, I think it would be useful to add the instruction 

`pip install -r requirements.txt `  

before 

`python setup.py install` 

And maybe add somehow that in the RSP we need to add --user to the two instructions above.

**Comment by sibirrer** [comment]
Thank you @alxogm for the feedback! The docs built was not triggered. I hope this part is fixed and is now in line with the github file. The pull request is also submitted for updating the documentation

**Comment by alxogm** [comment]
Yes, documentation pages now looks good! thank you for addressing the issue so quickly.

BTW the documentation for installing and how you expect work when making contributions is very clear and helpful. Thanks !
